# Generated by Django 5.2.3 on 2025-06-25 12:52

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(default=None, help_text='La date de naissance', verbose_name='Date de naissance')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Auteur'), ('lead', 'Acteur principal'), ('support', 'Acteur secondaire')], default='author', help_text='Role dans le film', verbose_name='Role')),
                ('author', models.ForeignKey(help_text='Auteur / Acteur du film', on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Auteur / Acteur')),
                ('movie', models.ForeignKey(help_text='Film', on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Film')),
            ],
        ),
    ]
