# Generated by Django 5.2.3 on 2025-06-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('movie', '0003_moviegenre_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authortomovie',
            name='author',
            field=models.ForeignKey(help_text='Auteur / Acteur du film', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='author.author', verbose_name='Auteur / Acteur'),
        ),
        migrations.AlterField(
            model_name='authortomovie',
            name='movie',
            field=models.ForeignKey(help_text='Film', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.movie', verbose_name='Film'),
        ),
    ]
