# Generated by Django 5.2.3 on 2025-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 'Un'), (2, 'Deux'), (3, 'Trois'), (4, 'Quatre'), (5, 'Cinq')], help_text='Note du film', verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 'Un'), (2, 'Deux'), (3, 'Trois'), (4, 'Quatre'), (5, 'Cinq')], default=1, help_text='Note du film', verbose_name='Note')),
            ],
        ),
    ]
