# Generated by Django 5.2.3 on 2025-06-25 12:52

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('movie', '0001_initial'),
        ('spectator', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(help_text="L'image du profil", null=True, upload_to='avatar', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Spectator',
                'verbose_name_plural': 'Spectators',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='authorreview',
            name='movie',
            field=models.ForeignKey(help_text='Film', on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Film'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='author',
            field=models.ForeignKey(help_text='Auteur / Acteur', on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Auteur / Acteur'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ForeignKey(help_text='Spectateur', on_delete=django.db.models.deletion.CASCADE, to='spectator.spectator', verbose_name='Spectateur'),
        ),
        migrations.AddField(
            model_name='authorreview',
            name='user',
            field=models.ForeignKey(help_text='Spectateur', on_delete=django.db.models.deletion.CASCADE, to='spectator.spectator', verbose_name='Spectateur'),
        ),
    ]
