# Generated by Django 5.2.3 on 2025-06-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('movie', '0003_moviegenre_remote_id'),
        ('spectator', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorreview',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='author',
        ),
        migrations.AddField(
            model_name='authorreview',
            name='author',
            field=models.ForeignKey(default=1, help_text='Auteur / Acteur', on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Auteur / Acteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(default=1, help_text='Film', on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Film'),
            preserve_default=False,
        ),
    ]
