# Generated by Django 5.2.3 on 2025-06-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_authortomovie_author_alter_authortomovie_movie'),
        ('movie', '0003_moviegenre_remote_id'),
        ('spectator', '0003_remove_authorreview_movie_remove_moviereview_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorreview',
            name='author',
            field=models.ForeignKey(help_text='Auteur / Acteur', on_delete=django.db.models.deletion.CASCADE, related_name='authorReviews', to='author.author', verbose_name='Auteur / Acteur'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(help_text='Film', on_delete=django.db.models.deletion.CASCADE, related_name='movieReviews', to='movie.movie', verbose_name='Film'),
        ),
    ]
