# Generated by Django 5.2.3 on 2025-06-25 12:52

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Le titre du film', max_length=100, verbose_name='Titre')),
                ('homepage', models.TextField(help_text='Le contenu de la page du film', max_length=2048, verbose_name='Homepage')),
                ('release_date', models.DateField(default=None, help_text='La date de parution du film', verbose_name='Date de sortie')),
                ('adult', models.BooleanField(help_text='Film réservé pour adultes', verbose_name='Pour adulte')),
                ('budget', models.IntegerField(default=0, help_text='Le budget du film', verbose_name='Budget')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('horror', 'Horreur'), ('western', 'Western'), ('mafia', 'Mafia'), ('fantasy', 'Fantastique'), ('sci-fi', 'Science Fiction'), ('historic', 'Historique'), ('cartoon', 'Dessin Animé'), ('comedy', 'Comédie')], help_text='Les genres du film', max_length=59, verbose_name='Genres')),
                ('status', models.TextField(choices=[('in_development', 'En développement'), ('in_production', 'En production'), ('published', 'publié'), ('cancelled', 'annulé')], default='in_development', help_text='Le statut du film', max_length=64, verbose_name='Statut')),
                ('cover', models.FileField(help_text="L'image de couverture du film'", null=True, upload_to='cover', verbose_name='Image de couverture')),
            ],
        ),
    ]
