# Generated by Django 5.2.3 on 2025-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviegenre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='remote_id',
            field=models.IntegerField(default=0),
        ),
    ]
